spring:
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10

server:
  tomcat:
    threads:
      max: 200

logging:
  level:
    com.catalog: INFO
    org.springframework: WARN
    org.hibernate: WARN
